# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/hmtcarga?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password:
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    #GMAIL
    mail:
        host: smtp.gmail.com
        port: 587
        username: someaccount@gmail.com  #Replace this field with your Gmail username.
        password: ******                 #Replace this field with your Gmail password.
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com

#    OUTLOOK
#     mail:
#             host: smtp-mail.outlook.com
#             port: 587
#             username: outlookuserid@outlook.com  #Replace this field with your Outlook username.
#             password: ************               #Replace this field with your Outlook password.
#             protocol: smtp
#             tls: true
#             properties.mail.smtp:
#                 auth: true
#                 starttls.enable: true
#                 ssl.trust: smtp-mail.outlook.com
#        [...] __Note__ : If you want to send Email from a Corporate Outlook account then set `host` as the Microsoft Exchange Server
#                 of your company, for e.g. `emea.mycompany.com`. Also set `username` as Standard Id of the system provided by the company
#                (Domain/Username) and `password` as your system password.
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false

liquibase:
    contexts: dev

server:
    port: 8080

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        ehcache:
            maxBytesLocalHeap: 16M
    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: ef47fe81bd0fad696c725d64dec4bf34b848b66e
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: hmtcarga@localhost
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: hmtcarga
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
